groups:
  - name: high_error_rate
    rules:
      - alert: HighHttpErrorRate
        expr: rate(http_errors_total[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 5m
        labels: {severity: critical}
  - name: scheduler_missed_runs
    rules:
      - alert: SchedulerMissedRuns
        expr: increase(tasks_collect_called_total[60m]) < 2
        for: 10m
        labels: {severity: warning}
