groups:
- name: aqi-alerts
  rules:
  - alert: HighHttpErrorRate
    expr: sum(rate(http_errors_total[5m])) / sum(rate(request_count[5m])) > 0.05
    for: 5m
    labels:
      severity: high
    annotations:
      description: HTTP error rate greater than 5% over 5m
  - alert: SchedulerMissedRuns
    expr: time() - aqi_job_last_run_seconds > 3600
    for: 60m
    labels:
      severity: critical
    annotations:
      description: Scheduler has not run in an hour
