name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd "pg_isready" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt
      - name: Lint
        run: flake8 pollution_data_visualizer || true
      - name: Run Python tests
        run: |
          PYTHONPATH=. pytest -q
        env:
          WAQI_TOKEN: dummy
          SECRET_KEY: test

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install JS dependencies
        run: npm ci
      - name: Run JS tests
        run: npm test

      - name: Build Docker image for smoke test
        run: docker build -t pollution_app_test .
      - name: Smoke test container
        run: |
          docker run -d --name test_cont -e WAQI_TOKEN=dummy -e SECRET_KEY=secret -p 8080:8080 pollution_app_test
          sleep 5
          curl -f http://localhost:8080/data/current?city=beijing
          curl -f http://localhost:8080/data/history
          docker rm -f test_cont
